// <auto-generated />
using CP_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CP_Final.Migrations
{
    [DbContext(typeof(FullContext))]
    [Migration("20230426021158_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CP_Final.Models.FavoriteFood", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"), 1L, 1);

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flavor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ForkSpoonHands")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("FavoriteFood");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            FavoriteFood = "Pasta",
                            FoodCategory = "Italian",
                            Flavor = "Spicy",
                            ForkSpoonHands = "Fork"
                        },
                        new
                        {
                            MemberID = 2,
                            FavoriteFood = "BBQ",
                            FoodCategory = "Korean",
                            Flavor = "Mild",
                            ForkSpoonHands = "Fork"
                        },
                        new
                        {
                            MemberID = 3,
                            FavoriteFood = "Steak",
                            FoodCategory = "American",
                            Flavor = "Mild",
                            ForkSpoonHands = "Fork"
                        });
                });

            modelBuilder.Entity("CP_Final.Models.Hobby", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"), 1L, 1);

                    b.Property<string>("Hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoursPerWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartedHobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("Hobby");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            Hobby = "Painting",
                            HoursPerWeek = "forty",
                            StartedHobby = "Photography",
                            Description = "I spend a lot of time painting"
                        },
                        new
                        {
                            MemberID = 2,
                            Hobby = "Video Games",
                            HoursPerWeek = "twenty",
                            StartedHobby = "Hiking",
                            Description = "I play video games after work"
                        },
                        new
                        {
                            MemberID = 3,
                            Hobby = "Golfing",
                            HoursPerWeek = "fifteen",
                            StartedHobby = "Traveling",
                            Description = "I like golfing with my friends"
                        });
                });

            modelBuilder.Entity("CP_Final.Models.TeamMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"), 1L, 1);

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Program")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberYear")
                        .HasColumnType("int");

                    b.HasKey("MemberID");

                    b.ToTable("TeamMember");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            BirthDate = "June 3rd 2003",
                            Program = "Information Technology",
                            MemberName = "Travis Scott",
                            MemberYear = 2025
                        },
                        new
                        {
                            MemberID = 2,
                            Birthdate = "January 12th 2002",
                            Program = "Drizzy",
                            MemberName = "Jacob khan",
                            MemberYear = 2025
                        },
                        new
                        {
                            MemberID = 3,
                            Birthdate = "January 22nd 2003",
                            Program = "Joji Alexander",
                            MemberName = "Dylan Mullarkey",
                            MemberYear = 2025
                        });
                });

            modelBuilder.Entity("CP_Final.Models.FavoriteSeason", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberID"), 1L, 1);

                    b.Property<string>("FavoriteSeason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weather")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Holidays")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberID");

                    b.ToTable("FavoriteSeason");

                    b.HasData(
                        new
                        {
                            MemberID = 1,
                            FavoriteSeason = "Winter",
                            Weather = "Cold",
                            Holidays = "Christmas",
                            Reason = "I like to play in snow"
                        },
                        new
                        {
                            MemberID = 2,
                            FavoriteSeason = "Summer",
                            Weather = "Warm",
                            Holidays = "Summer break",
                            Reason = "I like being able to wear shorts and go outside"
                        },
                        new
                        {
                            MemberID = 3,
                            FavoriteSeason = "Fall",
                            Weather = "Warm",
                            Holidays = "Christmas",
                            Reason = "I like Christmas holidays for the presents but I like fall season"
                        });
                });
                
#pragma warning restore 612, 618
        }
    }
}
